# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Repository', models.CharField(max_length=250)),
                ('Tag', models.CharField(max_length=200)),
                ('ImageId', models.CharField(max_length=200)),
                ('Function', models.CharField(max_length=200)),
                ('Size', models.CharField(default='NONE', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Instances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('TimeCreated', models.CharField(default='NONE', max_length=100)),
                ('Status', models.CharField(default='NONE', max_length=200)),
                ('ContainerId', models.CharField(default='NONE', max_length=100)),
                ('Image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfv.Images')),
            ],
        ),
        migrations.CreateModel(
            name='Interfaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('IP', models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4')),
                ('Mask', models.IntegerField(default=24)),
                ('Mac', models.CharField(default='NONE', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='instances',
            name='Interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfv.Interfaces'),
        ),
    ]
