# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='Repository',
        ),
    ]
