# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfv', '0003_images_repo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='Name',
            new_name='ImageName',
        ),
        migrations.RenameField(
            model_name='instances',
            old_name='Image',
            new_name='ImageName',
        ),
    ]
