# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfv', '0005_auto_20170404_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instances',
            name='Interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfv.Interfaces'),
        ),
    ]
