# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfv', '0006_auto_20170404_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instances',
            name='Interface',
        ),
        migrations.AddField(
            model_name='interfaces',
            name='InstanceName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfv.Instances'),
        ),
    ]
